spring:
  lifecycle:
    timeout-per-shutdown-phase: 1s
  cloud:
    function:
      definition: messageProducer
    stream:
      poller:
        fixed-delay: 1000
      bindings:
        messageProducer-out-0:
          destination: demo-topic-new
      kafka:
        binder:
          brokers:
            - localhost:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer